language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
branches:
  only:
    - master
notifications:
  email:
    - alaa.shafaee@prezi.com
    - balazs.dano@prezi.com
    - mohammed.showaib@prezi.com
    - ferenc.murcsik@prezi.com
